"use client";
import type { FormEvent } from "react";
import { useCallback, useEffect, useState } from "react";
import { BookCopy, ChevronLeft, ChevronRight, Edit3, LoaderCircle, Plus, Save, X } from "lucide-react";
import type { ApiFailure } from "@/lib/auth-types";
import type { CatalogEdition, CatalogItem, Paginated, Publisher } from "@/lib/admin-types";

function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}
function errorMessage(body:ApiFailure,fallback:string){return Array.isArray(body.message)?body.message.join(" "):body.message??fallback;}

export function AdminEditions(){
  const [editions,setEditions]=useState<CatalogEdition[]>([]),[items,setItems]=useState<CatalogItem[]>([]),[publishers,setPublishers]=useState<Publisher[]>([]);
  const [page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0); const [loading,setLoading]=useState(true),[editor,setEditor]=useState<CatalogEdition|"new"|null>(null),[notice,setNotice]=useState("");
  const load=useCallback(async(targetPage:number)=>{setLoading(true);try{const responses=await Promise.all([fetch(`/api/admin/catalog/editions?page=${targetPage}&limit=20`,{cache:"no-store"}),fetch("/api/admin/catalog/items?page=1&limit=100",{cache:"no-store"}),fetch("/api/admin/catalog/publishers?page=1&limit=100",{cache:"no-store"})]);const bodies=await Promise.all(responses.map((response)=>response.json()));for(let index=0;index<responses.length;index++)if(!responses[index].ok)throw new Error(errorMessage(bodies[index],"Não foi possível carregar as edições."));const editionPage=bodies[0] as Paginated<CatalogEdition>;setEditions(editionPage.data);setTotal(editionPage.meta.total);setPages(Math.max(1,editionPage.meta.totalPages));setItems((bodies[1] as Paginated<CatalogItem>).data);setPublishers((bodies[2] as Paginated<Publisher>).data);}catch(reason){setNotice(reason instanceof Error?reason.message:"Não foi possível carregar as edições.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(page),0);return()=>window.clearTimeout(timer);},[load,page]);
  return <div className="admin-page"><header className="admin-page__header"><div><p className="panel-eyebrow">Catálogo editorial</p><h1>Edições</h1><p>Registre idiomas, editoras, anos e identificadores de cada publicação.</p></div><button className="admin-primary-button" onClick={()=>setEditor("new")}><Plus/> Nova edição</button></header>{notice&&<p className="admin-notice admin-notice--error">{notice}</p>}<section className="admin-list-card"><header className="admin-list-toolbar"><div><strong>{total}</strong><span>edições cadastradas</span></div></header>{loading?<div className="admin-list-loading"><LoaderCircle className="spin"/> Carregando…</div>:editions.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Edição</th><th>Item</th><th>Idioma</th><th>Editora</th><th>Ano</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{editions.map((edition)=><tr key={edition.id}><td><strong>{edition.name}</strong><small>/{edition.slug}</small></td><td>{items.find((item)=>item.id===edition.catalogItemId)?.title??edition.catalogItemId}</td><td>{edition.languageCode}</td><td>{edition.publisher?.name??"—"}</td><td>{edition.releaseYear??"—"}</td><td><div className="admin-row-actions"><button onClick={()=>setEditor(edition)}><Edit3/></button></div></td></tr>)}</tbody></table></div>:<div className="admin-empty"><span className="admin-empty__icon"><BookCopy/></span><h2>Nenhuma edição cadastrada</h2></div>}<footer className="admin-pagination"><button onClick={()=>setPage((value)=>Math.max(1,value-1))} disabled={page<=1}><ChevronLeft/> Anterior</button><span>Página {page} de {pages}</span><button onClick={()=>setPage((value)=>Math.min(pages,value+1))} disabled={page>=pages}>Próxima <ChevronRight/></button></footer></section>{editor&&<EditionEditor key={editor==="new"?"new":editor.id} current={editor==="new"?null:editor} items={items} publishers={publishers} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);void load(page);}}/>}</div>;
}

function EditionEditor({current,items,publishers,onClose,onSaved}:{current:CatalogEdition|null;items:CatalogItem[];publishers:Publisher[];onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState(current?.name??""),[slug,setSlug]=useState(current?.slug??""),[touched,setTouched]=useState(Boolean(current)),[pending,setPending]=useState(false),[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const values=new FormData(event.currentTarget),year=String(values.get("releaseYear")??"");const body={catalogItemId:values.get("catalogItemId"),name,slug,languageCode:values.get("languageCode"),publisherId:String(values.get("publisherId")??"")||null,releaseYear:year?Number(year):null,isbn10:String(values.get("isbn10")??"")||null,isbn13:String(values.get("isbn13")??"")||null};try{const response=await fetch(current?`/api/admin/catalog/editions/${current.id}`:"/api/admin/catalog/editions",{method:current?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as ApiFailure;if(!response.ok)throw new Error(errorMessage(result,"Não foi possível salvar a edição."));onSaved();}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível salvar a edição.");}finally{setPending(false);}}
  return <div className="admin-dialog-backdrop"><section className="admin-dialog" role="dialog" aria-modal="true"><header><div><p className="panel-eyebrow">Publicação</p><h2>{current?"Editar edição":"Nova edição"}</h2></div><button onClick={onClose}><X/></button></header><form onSubmit={submit}><div className="admin-form-grid"><label>Item<select name="catalogItemId" defaultValue={current?.catalogItemId??""} required><option value="">Selecione</option>{items.map((item)=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Nome<input value={name} onChange={(event)=>{setName(event.target.value);if(!touched)setSlug(slugify(event.target.value));}} required maxLength={255}/></label><label>Slug<input value={slug} onChange={(event)=>{setTouched(true);setSlug(event.target.value);}} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label><label>Idioma<input name="languageCode" defaultValue={current?.languageCode??"pt-BR"} pattern="[a-z]{2,3}(?:-[A-Z]{2})?" required/></label><label>Editora<select name="publisherId" defaultValue={current?.publisher?.id??""}><option value="">Sem editora</option>{publishers.map((publisher)=><option value={publisher.id} key={publisher.id}>{publisher.name}</option>)}</select></label><label>Ano<input name="releaseYear" type="number" min={1900} max={2200} defaultValue={current?.releaseYear??""}/></label><label>ISBN-10<input name="isbn10" defaultValue={current?.isbn10??""} maxLength={20}/></label><label>ISBN-13<input name="isbn13" defaultValue={current?.isbn13??""} maxLength={20}/></label></div>{error&&<p className="admin-notice admin-notice--error">{error}</p>}<footer><button type="button" className="admin-quiet-button" onClick={onClose}>Cancelar</button><button className="admin-primary-button" disabled={pending}>{pending?<LoaderCircle className="spin"/>:<Save/>} Salvar</button></footer></form></section></div>;
}
