"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, BookHeart, Bookmark, CheckCircle2, ChevronLeft, ChevronRight, Eye, EyeOff, FolderHeart, Heart, Library, LoaderCircle, MessageSquareText, Pencil, Plus, Save, Star, Trash2 } from "lucide-react";
import { typeLabels } from "./catalog-data";
import type { AuthUser } from "@/lib/auth-types";
import type { PersonalCatalogItem, PersonalCollection, PersonalCollectionsResponse, PersonalItemsResponse, PersonalReview, PersonalReviewsResponse } from "@/lib/personal-types";
import { formatDate } from "@/lib/formatters";

type Notice = { type: "success" | "error"; text: string } | null;

async function request<T>(url: string, init?: RequestInit, unwrap = true): Promise<T> {
  const response = await fetch(url, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...init?.headers }, cache: "no-store" });
  const text = response.status === 204 ? "" : await response.text();
  const body = text ? JSON.parse(text) as { data?: T; message?: string | string[] } : {};
  if (!response.ok) throw Object.assign(new Error(Array.isArray(body.message) ? body.message.join(" ") : body.message ?? "Não foi possível concluir a ação."), { status: response.status });
  return (unwrap && "data" in body ? body.data : body) as T;
}

function useProtectedLoad(onLoad: () => Promise<void>) {
  const router = useRouter();
  useEffect(() => { const timer = window.setTimeout(() => { void onLoad().catch((error: Error & { status?: number }) => { if (error.status === 401) router.replace(`/entrar?returnTo=${encodeURIComponent(window.location.pathname)}`); }); }, 0); return () => window.clearTimeout(timer); }, [onLoad, router]);
}

const markerInfo = {
  hasItem: { label: "Tenho", icon: Library },
  wantsItem: { label: "Quero", icon: Bookmark },
  playedItem: { label: "Joguei", icon: CheckCircle2 },
  isFavorite: { label: "Favorito", icon: Heart },
} as const;
type Marker = keyof typeof markerInfo;

function NoticeLine({ notice }: { notice: Notice }) { return notice ? <p className={`form-message form-message--${notice.type}`} role="status">{notice.text}</p> : null; }
function AccountLoading() { return <div className="account-loading"><LoaderCircle className="spin" /> Consultando seus registros…</div>; }

export function LibraryView() {
  const [items, setItems] = useState<PersonalCatalogItem[]>([]); const [meta, setMeta] = useState<PersonalItemsResponse["meta"] | null>(null); const [filter, setFilter] = useState<Marker | "all">("all"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<Notice>(null); const [editing, setEditing] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ page: String(page), limit: "20" }); if (filter !== "all") params.set(filter, "true"); try { const result = await request<PersonalItemsResponse>(`/api/me/catalog/items?${params}`, undefined, false); setItems(result.data); setMeta(result.meta); } finally { setLoading(false); } }, [filter, page]);
  useProtectedLoad(load);
  async function toggle(entry: PersonalCatalogItem, marker: Marker) { setNotice(null); try { const updated = await request<PersonalCatalogItem>(`/api/me/catalog/items/${entry.catalogItem.id}`, { method: "PUT", body: JSON.stringify({ [marker]: !entry[marker] }) }); setItems((current) => current.map((item) => item.catalogItem.id === entry.catalogItem.id ? updated : item)); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível atualizar." }); } }
  async function saveComment(entry: PersonalCatalogItem, comment: string) { try { const updated = await request<PersonalCatalogItem>(`/api/me/catalog/items/${entry.catalogItem.id}`, { method: "PUT", body: JSON.stringify({ privateComment: comment || null }) }); setItems((current) => current.map((item) => item.catalogItem.id === entry.catalogItem.id ? updated : item)); setEditing(null); setNotice({ type: "success", text: "Comentário privado salvo." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível salvar." }); } }
  async function remove(entry: PersonalCatalogItem) { if (!window.confirm(`Remover “${entry.catalogItem.title}” de todas as suas listas?`)) return; try { await request(`/api/me/catalog/items/${entry.catalogItem.id}`, { method: "DELETE" }); setItems((current) => current.filter((item) => item.catalogItem.id !== entry.catalogItem.id)); setNotice({ type: "success", text: "Título removido da biblioteca." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível remover." }); } }
  return <><nav className="account-tabs" aria-label="Filtros da biblioteca"><button className={filter === "all" ? "active" : ""} onClick={() => { setFilter("all"); setPage(1); }}>Todos</button>{(Object.keys(markerInfo) as Marker[]).map((marker) => <button className={filter === marker ? "active" : ""} onClick={() => { setFilter(marker); setPage(1); }} key={marker}>{markerInfo[marker].label}</button>)}</nav><NoticeLine notice={notice} />{loading ? <AccountLoading /> : items.length ? <div className="library-list">{items.map((entry) => <article className="library-entry" key={entry.catalogItem.id}><div className="library-entry__sigil"><BookHeart /></div><div className="library-entry__main"><span>{typeLabels[entry.catalogItem.type]}</span><h2><Link href={`/catalogo/${entry.catalogItem.slug}`}>{entry.catalogItem.title}</Link></h2><div className="marker-row">{(Object.keys(markerInfo) as Marker[]).map((marker) => { const Icon = markerInfo[marker].icon; return <button className={entry[marker] ? "active" : ""} onClick={() => void toggle(entry, marker)} key={marker}><Icon fill={marker === "isFavorite" && entry[marker] ? "currentColor" : "none"} />{markerInfo[marker].label}</button>; })}</div>{editing === entry.catalogItem.id ? <form className="private-note" onSubmit={(event) => { event.preventDefault(); void saveComment(entry, String(new FormData(event.currentTarget).get("comment") ?? "")); }}><textarea name="comment" defaultValue={entry.privateComment ?? ""} maxLength={5000} placeholder="Anotação visível somente para você…" /><div><button type="button" onClick={() => setEditing(null)}>Cancelar</button><button type="submit"><Save /> Salvar</button></div></form> : entry.privateComment && <p className="private-note-preview"><MessageSquareText />{entry.privateComment}</p>}</div><div className="library-entry__actions"><button onClick={() => setEditing(editing === entry.catalogItem.id ? null : entry.catalogItem.id)} aria-label="Editar comentário"><Pencil /></button><button onClick={() => void remove(entry)} aria-label="Remover da biblioteca"><Trash2 /></button><Link href={`/catalogo/${entry.catalogItem.slug}`} aria-label="Abrir título"><ArrowRight /></Link></div></article>)}</div> : <div className="empty-state account-empty"><BookHeart /><h2>Sua biblioteca está esperando</h2><p>Adicione títulos pelo catálogo e combine os marcadores como preferir.</p><Link className="button-primary" href="/catalogo">Explorar catálogo</Link></div>}{meta && meta.totalPages > 1 && <nav className="pagination link-pagination"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft /> Anterior</button><span>Página {page} de {meta.totalPages}</span><button disabled={page >= meta.totalPages} onClick={() => setPage((value) => value + 1)}>Próxima <ChevronRight /></button></nav>}</>;
}

export function CollectionsView() {
  const [collections, setCollections] = useState<PersonalCollection[]>([]); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = useCallback(async () => { setLoading(true); try { const result = await request<PersonalCollectionsResponse>("/api/me/catalog/collections", undefined, false); setCollections(result.data); } finally { setLoading(false); } }, []); useProtectedLoad(load);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(null); const form = event.currentTarget; const data = new FormData(form); try { const collection = await request<PersonalCollection>("/api/me/catalog/collections", { method: "POST", body: JSON.stringify({ name: data.get("name"), description: data.get("description") || null, isPublic: data.get("isPublic") === "on" }) }); setCollections((current) => [collection, ...current]); setCreating(false); form.reset(); setNotice({ type: "success", text: "Coleção criada." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível criar." }); } }
  return <><div className="account-toolbar"><div><p className="panel-eyebrow">Organize suas histórias</p><h2>Suas coleções</h2></div><button className="button-primary" onClick={() => setCreating((value) => !value)}><Plus /> Nova coleção</button></div>{creating && <form className="collection-editor" onSubmit={create}><label>Nome<input name="name" maxLength={120} required /></label><label>Descrição<textarea name="description" maxLength={1000} /></label><label className="switch-line"><input type="checkbox" name="isPublic" /> Tornar esta coleção pública</label><div><button type="button" onClick={() => setCreating(false)}>Cancelar</button><button className="button-primary" type="submit">Criar coleção</button></div></form>}<NoticeLine notice={notice} />{loading ? <AccountLoading /> : collections.length ? <div className="collection-grid">{collections.map((collection) => <article className="collection-card" key={collection.id}><div className="collection-card__icon"><FolderHeart /></div><span className={collection.isPublic ? "public" : "private"}>{collection.isPublic ? <><Eye /> Pública</> : <><EyeOff /> Privada</>}</span><h2>{collection.name}</h2>{collection.description && <p>{collection.description}</p>}<footer><span>{collection.items.length} {collection.items.length === 1 ? "título" : "títulos"}</span><Link href={`/minhas-colecoes/${collection.id}`}>Abrir <ArrowRight /></Link></footer></article>)}</div> : <div className="empty-state account-empty"><FolderHeart /><h2>Nenhuma coleção criada</h2><p>Crie estantes temáticas para organizar seus títulos.</p><button className="button-primary" onClick={() => setCreating(true)}>Criar primeira coleção</button></div>}</>;
}

export function CollectionDetailView({ collectionId }: { collectionId: string }) {
  const router = useRouter(); const [collection, setCollection] = useState<PersonalCollection | null>(null); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = useCallback(async () => { setLoading(true); try { setCollection(await request<PersonalCollection>(`/api/me/catalog/collections/${collectionId}`)); } finally { setLoading(false); } }, [collectionId]); useProtectedLoad(load);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const updated = await request<PersonalCollection>(`/api/me/catalog/collections/${collectionId}`, { method: "PATCH", body: JSON.stringify({ name: data.get("name"), description: data.get("description") || null, isPublic: data.get("isPublic") === "on" }) }); setCollection(updated); setEditing(false); setNotice({ type: "success", text: "Coleção atualizada." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível salvar." }); } }
  async function removeItem(itemId: string) { try { await request(`/api/me/catalog/collections/${collectionId}/items/${itemId}`, { method: "DELETE" }); setCollection((current) => current ? { ...current, items: current.items.filter(({ item }) => item.id !== itemId) } : current); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível remover." }); } }
  async function removeCollection() { if (!collection || !window.confirm(`Excluir definitivamente “${collection.name}”?`)) return; try { await request(`/api/me/catalog/collections/${collectionId}`, { method: "DELETE" }); router.push("/minhas-colecoes"); router.refresh(); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível excluir." }); } }
  if (loading) return <AccountLoading />; if (!collection) return <div className="empty-state account-empty"><FolderHeart /><h2>Coleção indisponível</h2></div>;
  return <><div className="collection-detail-head"><div><span className={collection.isPublic ? "public" : "private"}>{collection.isPublic ? "Pública" : "Privada"}</span><h1>{collection.name}</h1><p>{collection.description ?? "Sem descrição."}</p></div><div>{collection.isPublic && <Link className="button-secondary" href={`/colecoes/${collection.id}`}>Ver página pública</Link>}<button className="button-secondary" onClick={() => setEditing((value) => !value)}><Pencil /> Editar</button><button className="danger-button" onClick={() => void removeCollection()}><Trash2 /> Excluir</button></div></div>{editing && <form className="collection-editor" onSubmit={save}><label>Nome<input name="name" defaultValue={collection.name} maxLength={120} required /></label><label>Descrição<textarea name="description" defaultValue={collection.description ?? ""} maxLength={1000} /></label><label className="switch-line"><input type="checkbox" name="isPublic" defaultChecked={collection.isPublic} /> Coleção pública</label><div><button type="button" onClick={() => setEditing(false)}>Cancelar</button><button className="button-primary" type="submit">Salvar alterações</button></div></form>}<NoticeLine notice={notice} /><header className="account-section-head"><h2>Títulos da coleção</h2><span>{collection.items.length} itens</span></header>{collection.items.length ? <div className="collection-items">{collection.items.map(({ item, position }) => <article key={item.id}><span>{String(position).padStart(2, "0")}</span><div><small>{typeLabels[item.type]}</small><h3><Link href={`/catalogo/${item.slug}`}>{item.title}</Link></h3></div><button onClick={() => void removeItem(item.id)} aria-label={`Remover ${item.title}`}><Trash2 /></button></article>)}</div> : <div className="empty-state account-empty"><FolderHeart /><h2>Coleção vazia</h2><p>Adicione títulos pelo painel disponível em cada página do catálogo.</p><Link className="button-primary" href="/catalogo">Explorar catálogo</Link></div>}</>;
}

export function ReviewsView() {
  const [reviews, setReviews] = useState<PersonalReview[]>([]); const [meta, setMeta] = useState<PersonalReviewsResponse["meta"] | null>(null); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [editing, setEditing] = useState<string | null>(null); const [notice, setNotice] = useState<Notice>(null);
  const load = useCallback(async () => { setLoading(true); try { const result = await request<PersonalReviewsResponse>(`/api/me/catalog/reviews?page=${page}&limit=20`, undefined, false); setReviews(result.data); setMeta(result.meta); } finally { setLoading(false); } }, [page]); useProtectedLoad(load);
  async function save(review: PersonalReview, event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const updated = await request<PersonalReview>(`/api/me/catalog/reviews/${review.catalogItem.id}`, { method: "PUT", body: JSON.stringify({ rating: Number(data.get("rating")), content: data.get("content") || null }) }); setReviews((current) => current.map((item) => item.id === review.id ? { ...updated, catalogItem: review.catalogItem } : item)); setEditing(null); setNotice({ type: "success", text: "Avaliação enviada novamente para moderação." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível salvar." }); } }
  async function remove(review: PersonalReview) { if (!window.confirm("Excluir esta avaliação?")) return; try { await request(`/api/me/catalog/reviews/${review.catalogItem.id}`, { method: "DELETE" }); setReviews((current) => current.filter((item) => item.id !== review.id)); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível excluir." }); } }
  return <><NoticeLine notice={notice} />{loading ? <AccountLoading /> : reviews.length ? <div className="my-review-list">{reviews.map((review) => <article key={review.id}><header><div><span className={`review-status review-status--${review.status.toLowerCase()}`}>{review.status === "PENDING" ? "Em moderação" : review.status === "PUBLISHED" ? "Publicada" : "Rejeitada"}</span><h2>{review.catalogItem.slug ? <Link href={`/catalogo/${review.catalogItem.slug}`}>{review.catalogItem.title}</Link> : review.catalogItem.title ?? "Título"}</h2></div><strong><Star fill="currentColor" />{review.rating}/10</strong></header>{editing === review.id ? <form onSubmit={(event) => void save(review, event)}><label>Nota<input name="rating" type="number" min="1" max="10" defaultValue={review.rating} required /></label><label>Comentário<textarea name="content" defaultValue={review.content ?? ""} maxLength={5000} /></label><div><button type="button" onClick={() => setEditing(null)}>Cancelar</button><button className="button-primary" type="submit">Salvar e reenviar</button></div></form> : <><p>{review.content ?? "Avaliação sem comentário."}</p>{review.moderationReason && <aside><strong>Motivo da moderação:</strong> {review.moderationReason}</aside>}<footer><time>{formatDate(review.updatedAt)}</time><div><button onClick={() => setEditing(review.id)}><Pencil /> Editar</button><button onClick={() => void remove(review)}><Trash2 /> Excluir</button></div></footer></>}</article>)}</div> : <div className="empty-state account-empty"><MessageSquareText /><h2>Você ainda não avaliou nenhum título</h2><p>Abra um item do catálogo para publicar sua primeira avaliação.</p><Link className="button-primary" href="/catalogo">Explorar catálogo</Link></div>}{meta && meta.totalPages > 1 && <nav className="pagination link-pagination"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Anterior</button><span>Página {page} de {meta.totalPages}</span><button disabled={page >= meta.totalPages} onClick={() => setPage((value) => value + 1)}>Próxima</button></nav>}</>;
}

export function ItemPersonalActions({ itemId, itemSlug }: { itemId: string; itemSlug: string }) {
  const [user, setUser] = useState<AuthUser | null | undefined>(undefined); const [entry, setEntry] = useState<PersonalCatalogItem | null>(null); const [collections, setCollections] = useState<PersonalCollection[]>([]); const [review, setReview] = useState<PersonalReview | null>(null); const [notice, setNotice] = useState<Notice>(null); const [pending, setPending] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { void (async () => { const session = await request<AuthUser | null>("/api/auth/session"); setUser(session); if (!session) return; const [itemsResult, collectionsResult, reviewsResult] = await Promise.all([request<PersonalItemsResponse>("/api/me/catalog/items?limit=100", undefined, false), request<PersonalCollectionsResponse>("/api/me/catalog/collections", undefined, false), request<PersonalReviewsResponse>("/api/me/catalog/reviews?limit=100", undefined, false)]); setEntry(itemsResult.data.find((item) => item.catalogItem.id === itemId) ?? null); setCollections(collectionsResult.data); setReview(reviewsResult.data.find((item) => item.catalogItem.id === itemId) ?? null); })().catch(() => setUser(null)); }, 0); return () => window.clearTimeout(timer); }, [itemId]);
  async function marker(marker: Marker) { setPending(true); setNotice(null); try { const updated = await request<PersonalCatalogItem>(`/api/me/catalog/items/${itemId}`, { method: "PUT", body: JSON.stringify({ [marker]: !(entry?.[marker] ?? false) }) }); setEntry(updated); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível atualizar." }); } finally { setPending(false); } }
  async function comment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { setEntry(await request<PersonalCatalogItem>(`/api/me/catalog/items/${itemId}`, { method: "PUT", body: JSON.stringify({ privateComment: data.get("privateComment") || null }) })); setNotice({ type: "success", text: "Anotação privada salva." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível salvar." }); } finally { setPending(false); } }
  async function evaluate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { setReview(await request<PersonalReview>(`/api/me/catalog/reviews/${itemId}`, { method: "PUT", body: JSON.stringify({ rating: Number(data.get("rating")), content: data.get("content") || null }) })); setNotice({ type: "success", text: "Avaliação enviada para moderação." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível avaliar." }); } finally { setPending(false); } }
  async function addCollection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const collectionId = String(new FormData(event.currentTarget).get("collectionId")); if (!collectionId) return; setPending(true); try { await request(`/api/me/catalog/collections/${collectionId}/items/${itemId}`, { method: "POST", body: JSON.stringify({ position: 0 }) }); setCollections((current) => current.map((collection) => collection.id === collectionId ? { ...collection, items: [...collection.items, { position: 0, item: { id: itemId, slug: itemSlug, title: "", type: "TOOL" } }] } : collection)); setNotice({ type: "success", text: "Título adicionado à coleção." }); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Não foi possível adicionar." }); } finally { setPending(false); } }
  if (user === undefined) return <section id="minha-estante" className="personal-actions"><AccountLoading /></section>;
  if (!user) return <section id="minha-estante" className="personal-actions personal-actions--guest"><div><p className="panel-eyebrow">Sua estante</p><h2>Guarde esta descoberta</h2><p>Entre para marcar, avaliar e adicionar este título às suas coleções.</p></div><Link className="button-primary" href={`/entrar?returnTo=${encodeURIComponent(`/catalogo/${itemSlug}#minha-estante`)}`}>Entrar na Guilda</Link></section>;
  const availableCollections = collections.filter((collection) => !collection.items.some(({ item }) => item.id === itemId));
  return <section id="minha-estante" className="personal-actions"><header><div><p className="panel-eyebrow">Sua estante</p><h2>Organize este título</h2></div><span>Olá, {user.name.split(" ")[0]}</span></header><NoticeLine notice={notice} /><div className="personal-marker-grid">{(Object.keys(markerInfo) as Marker[]).map((key) => { const Icon = markerInfo[key].icon; const active = entry?.[key] ?? false; return <button className={active ? "active" : ""} disabled={pending} onClick={() => void marker(key)} key={key}><Icon fill={key === "isFavorite" && active ? "currentColor" : "none"} /><span>{markerInfo[key].label}</span></button>; })}</div><div className="personal-action-columns"><form onSubmit={comment}><h3>Anotação privada</h3><textarea name="privateComment" defaultValue={entry?.privateComment ?? ""} maxLength={5000} placeholder="Somente você poderá ler…" /><button className="button-secondary" disabled={pending} type="submit"><Save /> Salvar anotação</button></form><form onSubmit={evaluate}><h3>{review ? "Editar avaliação" : "Avaliar título"}</h3><label>Nota de 1 a 10<input name="rating" type="number" min="1" max="10" defaultValue={review?.rating ?? 10} required /></label><textarea name="content" defaultValue={review?.content ?? ""} maxLength={5000} placeholder="Compartilhe sua experiência…" /><button className="button-secondary" disabled={pending} type="submit"><Star /> {review ? "Salvar e reenviar" : "Enviar avaliação"}</button>{review && <small>Status atual: {review.status}</small>}</form><form onSubmit={addCollection}><h3>Adicionar à coleção</h3>{availableCollections.length ? <><select name="collectionId" required><option value="">Escolha uma coleção</option>{availableCollections.map((collection) => <option value={collection.id} key={collection.id}>{collection.name}</option>)}</select><button className="button-secondary" disabled={pending} type="submit"><Plus /> Adicionar</button></> : <p>Todos os seus acervos já contêm este título, ou você ainda não criou uma coleção.</p>}<Link href="/minhas-colecoes">Gerenciar coleções <ArrowRight /></Link></form></div></section>;
}
